package com.mobile.emoticon.fast.emoji

object EmojiDataUtils {
    val iconFace = listOf(
        R.drawable.icon_emjioface_1,
        R.drawable.icon_emjioface_2,
        R.drawable.icon_emjioface_3,
        R.drawable.icon_emjioface_4,
        R.drawable.icon_emjioface_5,
        R.drawable.icon_emjioface_6,
    )
    val iconEye = listOf(
        R.drawable.icon_emjioeye_22,
        R.drawable.icon_emjioeye_23,
        R.drawable.icon_emjioeye_24,
        R.drawable.icon_emjioeye_25,
        R.drawable.icon_emjioeye_26,
        R.drawable.icon_emjioeye_27,
    )

    val iconHand = listOf(
        R.drawable.icon_emjiohand_5,
        R.drawable.icon_emjiohand_6,
        R.drawable.icon_emjiohand_7,
        R.drawable.icon_emjiohand_8,
        R.drawable.icon_emjiohand_9,
        R.drawable.icon_emjiohand_10,
    )
    val iconMouth = listOf(
        R.drawable.icon_emjiomouth_23,
        R.drawable.icon_emjiomouth_24,
        R.drawable.icon_emjiomouth_25,
        R.drawable.icon_emjiomouth_26,
        R.drawable.icon_emjiomouth_27,
        R.drawable.icon_emjiomouth_28,
    )

    val iconFlower = listOf(
        R.drawable.ic_emoji_flower_1,
        R.drawable.ic_emoji_flower_2,
        R.drawable.ic_emoji_flower_3,
        R.drawable.ic_emoji_flower_4,
        R.drawable.ic_emoji_flower_5,
        R.drawable.ic_emoji_flower_6,
        R.drawable.ic_emoji_flower_7,
        R.drawable.ic_emoji_flower_8,
        R.drawable.ic_emoji_flower_9,
        R.drawable.ic_emoji_flower_10,
        R.drawable.ic_emoji_flower_11,
        R.drawable.ic_emoji_flower_12,
        R.drawable.ic_emoji_flower_13,
        R.drawable.ic_emoji_flower_14,
        R.drawable.ic_emoji_flower_15,
        R.drawable.ic_emoji_flower_16,
        R.drawable.ic_emoji_flower_17,
        R.drawable.ic_emoji_flower_18,
        R.drawable.ic_emoji_flower_19,
        R.drawable.ic_emoji_flower_20,
        R.drawable.ic_emoji_flower_other_1,
        R.drawable.ic_emoji_flower_other_2,
        R.drawable.ic_emoji_flower_other_3,
        R.drawable.ic_emoji_flower_other_4,
        R.drawable.ic_emoji_flower_other_5,
        R.drawable.ic_emoji_flower_other_6,
        R.drawable.ic_emoji_flower_other_7,
        R.drawable.ic_emoji_flower_other_8,
        R.drawable.ic_emoji_flower_other_9,
        R.drawable.ic_emoji_flower_other_10,
        R.drawable.ic_emoji_flower_other_11,
        R.drawable.ic_emoji_flower_other_12,
        R.drawable.ic_emoji_flower_other_13,
        R.drawable.ic_emoji_flower_other_14,
        R.drawable.ic_emoji_flower_other_15,
        R.drawable.ic_emoji_flower_other_16,
        R.drawable.ic_emoji_flower_other_17,
    )
    val iconFoot = listOf(
        R.drawable.ic_emoji_foot_1,
        R.drawable.ic_emoji_foot_2,
        R.drawable.ic_emoji_foot_3,
        R.drawable.ic_emoji_foot_4,
        R.drawable.ic_emoji_foot_5,
        R.drawable.ic_emoji_foot_6,
        R.drawable.ic_emoji_foot_7,
        R.drawable.ic_emoji_foot_8,
        R.drawable.ic_emoji_foot_9,
        R.drawable.ic_emoji_foot_10,
        R.drawable.ic_emoji_foot_11,
        R.drawable.ic_emoji_foot_12,
        R.drawable.ic_emoji_foot_13,
        R.drawable.ic_emoji_foot_14,
        R.drawable.ic_emoji_foot_15,
        R.drawable.ic_emoji_foot_16,
        R.drawable.ic_emoji_foot_17,
        R.drawable.ic_emoji_foot_18,
        R.drawable.ic_emoji_foot_19,
        R.drawable.ic_emoji_foot_20,
        R.drawable.ic_emoji_foot_21,
        R.drawable.ic_emoji_foot_22,
        R.drawable.ic_emoji_foot_23,
        R.drawable.ic_emoji_foot_24,
        R.drawable.ic_emoji_foot_25,
        R.drawable.ic_emoji_foot_26,
        R.drawable.ic_emoji_foot_27,
        R.drawable.ic_emoji_foot_28,
    )
    val iconFruits = listOf(
        R.drawable.ic_emoji_fruits_1,
        R.drawable.ic_emoji_fruits_2,
        R.drawable.ic_emoji_fruits_3,
        R.drawable.ic_emoji_fruits_4,
        R.drawable.ic_emoji_fruits_5,
        R.drawable.ic_emoji_fruits_6,
        R.drawable.ic_emoji_fruits_7,
        R.drawable.ic_emoji_fruits_8,
        R.drawable.ic_emoji_fruits_9,
        R.drawable.ic_emoji_fruits_10,
        R.drawable.ic_emoji_fruits_11,
        R.drawable.ic_emoji_fruits_12,
        R.drawable.ic_emoji_fruits_13,
        R.drawable.ic_emoji_fruits_14,
        R.drawable.ic_emoji_fruits_15,
        R.drawable.ic_emoji_fruits_16,
        R.drawable.ic_emoji_fruits_17,
        R.drawable.ic_emoji_fruits_18,
        R.drawable.ic_emoji_fruits_19,
        R.drawable.ic_emoji_fruits_20,
        R.drawable.ic_emoji_fruits_21,
        R.drawable.ic_emoji_fruits_22,
    )
    val iconHeart = listOf(
        R.drawable.ic_emoji_heart_1,
        R.drawable.ic_emoji_heart_2,
        R.drawable.ic_emoji_heart_3,
        R.drawable.ic_emoji_heart_4,
        R.drawable.ic_emoji_heart_5,
        R.drawable.ic_emoji_heart_6,
        R.drawable.ic_emoji_heart_7,
        R.drawable.ic_emoji_heart_8,
        R.drawable.ic_emoji_heart_9,
        R.drawable.ic_emoji_heart_10,
        R.drawable.ic_emoji_heart_11,
        R.drawable.ic_emoji_heart_12,
        R.drawable.ic_emoji_heart_13,
        R.drawable.ic_emoji_heart_14,
        R.drawable.ic_emoji_heart_15,
        R.drawable.ic_emoji_heart_16,
    )


    val iconBear = listOf(
        R.drawable.ic_bear_1,
        R.drawable.ic_bear_2,
        R.drawable.ic_bear_3,
        R.drawable.ic_bear_4,
        R.drawable.ic_bear_5,
        R.drawable.ic_bear_6,
    )

    val iconCat = listOf(
        R.drawable.ic_cat_1,
        R.drawable.ic_cat_2,
        R.drawable.ic_cat_3,
        R.drawable.ic_cat_4,
        R.drawable.ic_cat_5,
        R.drawable.ic_cat_6,
    )

    val iconRabbit = listOf(
        R.drawable.ic_rabbit_1,
        R.drawable.ic_rabbit_2,
        R.drawable.ic_rabbit_3,
        R.drawable.ic_rabbit_4,
        R.drawable.ic_rabbit_5,
        R.drawable.ic_rabbit_6,
        R.drawable.ic_rabbit_7,
        R.drawable.ic_rabbit_8,
    )
}